### ISSUE TITLE
Project Feedback!

### ISSUE THREAD

**Issue by codepathreview** [amatsuba1222/TwitterApp#1]
Hello Aoi, 

Looks like your submitted Github repo is missing some of the app code. Please [push your code to Github](https://courses.codepath.com/courses/intro_to_android/pages/submitting_assignments#heading-pushing-code) and then [re-submit your project](https://courses.codepath.com/courses/intro_to_android/pages/submitting_assignments#heading-submitting-through-course-system) through the course system.

**Comment by amatsuba1222** [comment]
Hi,
Sorry I didn't push all the files for some reason. I repushed all of it for sure now, and resubmitted the assignment. 
Please take a look at my repo again. 

Thank you,
Aoi

**Comment by codepathreview** [comment]
:+1: nice work. A few notes after checking out the code:

* Nice to see you successfully used OAuth login. OAuth is widely used and it's important to understand OAuth v1 and v2 properly.
* Good to see you were able to format the timestamp cleanly.
* Good to see you added the new tweet directly to the home timeline after it was successfully posted to Twitter.
* Nice touch with the character count being displayed while the user composes a tweet.
* Consider adding local persistence of tweets by using DBFlow in the `Tweet` and `User`. See the [persistence guide](http://guides.codepath.com/android/Persisting-Data-to-the-Device#object-relational-mappers) and this [other guide](http://guides.codepath.com/android/DBFlow-Guide) for more details.
* Consider using [GSON](https://guides.codepath.com/android/Leveraging-the-Gson-Library) to conveniently serialize and deserialize API responses into objects.
* Consider using the folder structure and naming conventions defined in http://guides.codepath.com/android/Organizing-your-Source-Files.
* Try out the third-party [ButterKnife](https://guides.codepath.com/android/Reducing-View-Boilerplate-with-Butterknife) library to simplify a lot of boilerplate `findViewById()` calls.

Here's a detailed [Project 3 Feedback Guide here](http://courses.codepath.com/snippets/intro_to_android/project_3_feedback) which covers the most common issues with this submitted project. Read through the feedback guide point-by-point to determine how you could improve your submission. 

Let us know if you have any other thoughts or questions about this assignment. Hopefully by now you feel pretty comfortable with all the major pieces to basic Android apps (Views, Controllers, ActionBar, Navigation, Models, Authentication, API Communication, Persistence, et al) and see how they all fit together. We are close now to a turning point in the course where you should be hitting a "critical mass" towards your knowledge of Android.
